alter session set "_oracle_script"=true;

---- Use the schema
ALTER SESSION SET CURRENT_SCHEMA = Ql_Billiard;


--drop table account
-- Create Account table
CREATE TABLE Account (
    TaiKhoan VARCHAR2(20) PRIMARY KEY,
    MatKhau VARCHAR2(50) NOT NULL,
    HoTen NVARCHAR2(50),
    SDT CHAR(10) NOT NULL CHECK (REGEXP_LIKE(SDT, '^\d{10}$')),
    TinhTrang NVARCHAR2(50) CHECK (TinhTrang IN ('Đang làm việc', 'Nghỉ việc')),
    QuanLy NUMBER(1)
);

CREATE TABLE TrangThai(
    MaTrangThai NUMBER PRIMARY KEY,
    TenTrangThai NVARCHAR2(50)
)

CREATE TABLE loaiban(
    MaLoai CHAR(10) PRIMARY KEY,
    TenLoai NVARCHAR2(20)
)

-- Create Ban table
CREATE TABLE Ban (
    MaBan CHAR(10) PRIMARY KEY,
    TenBan NVARCHAR2(20),
    LoaiBan CHAR(10),
    TrangThai NUMBER,
    Gia FLOAT CHECK (Gia > 0),
    HinhAnh NVARCHAR2(50),
    CONSTRAINT fk_ban_loaiban FOREIGN KEY (LoaiBan) REFERENCES LoaiBan(MaLoai),
    CONSTRAINT fk_ban_trangthai FOREIGN KEY (TrangThai) REFERENCES TrangThai(MaTrangThai)
);

CREATE TABLE ThucDon (
    MaThucDon CHAR(5) PRIMARY KEY,
    TenThucDon NVARCHAR2(50) NOT NULL,
    DonViTinh NVARCHAR2(10) NOT NULL,
    Gia FLOAT NOT NULL CHECK (Gia > 0),
    Hinh NVARCHAR2(1000),
    GhiChu NVARCHAR2(100)
);


CREATE TABLE LoaiThanhVien(
    MaLoaiTV NUMBER PRIMARY KEY,
    TenLoaiTV NVARCHAR2(50),
    GiamGia FLOAT,
    GhiChu NVARCHAR2(50)
)

---- Create KhachHang table
CREATE TABLE KhachHang (
    MaKH NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ten NVARCHAR2(50) NOT NULL,
    Phone CHAR(10) CHECK (REGEXP_LIKE(Phone, '^\d{10}$')),
    LoaiThanhVien NUMBER,
    CONSTRAINT fk_khachhang_loaitv FOREIGN KEY (LoaiThanhVien) REFERENCES LoaiThanhVien(MaLoaiTV)
);

-- Create HoaDon table
CREATE TABLE HoaDon (
    MaHoaDon NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaBan CHAR(10) NOT NULL,
    GioBatDau TIMESTAMP,
    GioKetThuc TIMESTAMP,
    ThoiGianChoi NUMBER CHECK (ThoiGianChoi > 0),
    ThanhToan FLOAT,
    KhachHang NUMBER NOT NULL,
    TongTien FLOAT CHECK (TongTien > 0),
    GhiChu NVARCHAR2(100),
    TrangThaiThanhToan NVARCHAR2(20) CHECK (TrangThaiThanhToan IN ('Chưa Thanh Toán', 'Đã Thanh Toán')),
    TaiKhoan VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_hoadon_ban FOREIGN KEY (MaBan) REFERENCES Ban(MaBan),
    CONSTRAINT fk_hoadon_KhachHang FOREIGN KEY (KhachHang) REFERENCES KhachHang(MaKH),
    CONSTRAINT fk_hoadon_Account FOREIGN KEY (TaiKhoan) REFERENCES Account(TaiKhoan),
    CONSTRAINT chk_GioKetThuc CHECK (GioBatDau < GioKetThuc)
);
-- Create ChiTietHoaDon table
CREATE TABLE ChiTietHoaDon (
    MaChiTietHoaDon NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaHoaDon NUMBER NOT NULL,
    MaThucDon CHAR(5) NOT NULL,
    SoLuongDat NUMBER NOT NULL,
    CONSTRAINT fk_chitiet_hd FOREIGN KEY (MaHoaDon) REFERENCES HoaDon(MaHoaDon),
    CONSTRAINT fk_chitiet_td FOREIGN KEY (MaThucDon) REFERENCES ThucDon(MaThucDon)
);
-- Create DatTruoc table
CREATE TABLE DatTruoc (
    MaDatTruoc NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKH NUMBER NOT NULL,
    MaBan CHAR(10) NOT NULL,
    ThoiGianToi TIMESTAMP NOT NULL ,
    NgayDat TIMESTAMP NOT NULL,
    GhiChu NVARCHAR2(100),
    CONSTRAINT fk_DatTruoc_kh FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    CONSTRAINT fk_DatTruoc_ban FOREIGN KEY (MaBan) REFERENCES Ban(MaBan)
);

INSERT INTO Account VALUES ('MainAdmin','14', N'Huỳnh Long', '0367353929', N'Đang làm việc', 1);
INSERT INTO Ql_Billiard.Account VALUES ('userStaff1','14',  N'Đình Tiến', '0367353930', N'Đang làm việc', 0);



INSERT INTO TrangThai (MaTrangThai, TenTrangThai) VALUES (0, N'Không hoạt động');
INSERT INTO TrangThai (MaTrangThai, TenTrangThai) VALUES (1, N'Còn trống');
INSERT INTO TrangThai (MaTrangThai, TenTrangThai) VALUES (2, N'Đang chơi');
INSERT INTO TrangThai (MaTrangThai, TenTrangThai) VALUES (3, N'Đã đặt');


INSERT INTO LoaiBan (MaLoai, TenLoai) VALUES ('Lo', N'Lỗ');
INSERT INTO LoaiBan (MaLoai, TenLoai) VALUES ('Lip', N'Bàn Lip');
INSERT INTO LoaiBan (MaLoai, TenLoai) VALUES ('Carom', N'Bàn 3 băng');


-- Thêm dữ liệu vào bảng Ban
INSERT INTO Ban (MaBan, TenBan, LoaiBan, TrangThai, Gia, HinhAnh) VALUES ('BAN01', N'Bàn 1', N'Lo', 1, 70000, 'banbidalo.png');
INSERT INTO Ban (MaBan, TenBan, LoaiBan, TrangThai, Gia, HinhAnh) VALUES ('BAN02', N'Bàn 2', N'Lo', 1, 70000, 'banbidalo.png');
INSERT INTO Ban (MaBan, TenBan, LoaiBan, TrangThai, Gia, HinhAnh) VALUES ('BAN03', N'Bàn 3', N'Lo', 1, 70000, 'banbidalo.png');
INSERT INTO Ban (MaBan, TenBan, LoaiBan, TrangThai, Gia, HinhAnh) VALUES ('BAN04', N'Bàn 4', N'Lo', 1, 70000, 'banbidalo.png');
INSERT INTO Ban (MaBan, TenBan, LoaiBan, TrangThai, Gia, HinhAnh) VALUES ('BAN05', N'Bàn 5', N'Lip', 1, 50000, 'banbidaphang.png');
INSERT INTO Ban (MaBan, TenBan, LoaiBan, TrangThai, Gia, HinhAnh) VALUES ('BAN06', N'Bàn 6', N'Lip', 1, 50000, 'banbidaphang.png');
INSERT INTO Ban (MaBan, TenBan, LoaiBan, TrangThai, Gia, HinhAnh) VALUES ('BAN07', N'Bàn 7', N'Carom', 1, 60000, 'banbida3bang.png');
INSERT INTO Ban (MaBan, TenBan, LoaiBan, TrangThai, Gia, HinhAnh) VALUES ('BAN08', N'Bàn 8', N'Carom', 1, 60000, 'banbida3bang.png');


INSERT INTO LoaiThanhVien (MaLoaiTV, TenLoaiTV, GiamGia, GhiChu) VALUES (0, N'Khách vãng lai', 0, N'Không giảm giá');
INSERT INTO LoaiThanhVien (MaLoaiTV, TenLoaiTV, GiamGia, GhiChu) VALUES (1, N'Đã đăng kí thành viên', 0.1, N'Giảm mười phẩn trăm');
INSERT INTO LoaiThanhVien (MaLoaiTV, TenLoaiTV, GiamGia, GhiChu) VALUES (2, N'Học sinh / sinh viên', 0.3, N'Giảm ba mươi phẩn trăm');


-- Thêm dữ liệu vào bảng KhachHang
INSERT INTO KhachHang (Ten, Phone, LoaiThanhVien) VALUES (N'Khách lạ', NULL, 0);
INSERT INTO KhachHang (Ten, Phone, LoaiThanhVien) VALUES (N'Lê Thị B', '0000000000', 1);
INSERT INTO KhachHang (Ten, Phone, LoaiThanhVien) VALUES (N'Tiến xinh zai', '1111111111', 2);



-- inset data account


-- Thêm dữ liệu vào bảng ThucDon
INSERT INTO ThucDon (MaThucDon, TenThucDon, DonViTinh, Gia) VALUES ('TD01', N'Trà đá', N'Ca', 15000);
INSERT INTO ThucDon (MaThucDon, TenThucDon, DonViTinh, Gia) VALUES ('TD02', N'Trà sữa', N'Ly', 25000);
INSERT INTO ThucDon (MaThucDon, TenThucDon, DonViTinh, Gia) VALUES ('TD03', N'Cơm', N'Đĩa', 35000);


-- Thêm dữ liệu vào bảng HoaDon
INSERT INTO HoaDon (MaBan, GioBatDau, GioKetThuc, KhachHang, GhiChu, TrangThaiThanhToan, TaiKhoan) 
VALUES ('BAN01', TO_DATE('2024-05-17T17:00:00', 'YYYY-MM-DD"T"HH24:MI:SS'), TO_DATE('2024-05-17T17:30:00', 'YYYY-MM-DD"T"HH24:MI:SS'), 0, NULL, N'Chưa Thanh Toán', 'staff');

INSERT INTO HoaDon (MaBan, GioBatDau, GioKetThuc, KhachHang, GhiChu, TrangThaiThanhToan, TaiKhoan)  
VALUES ('BAN02', TO_DATE('2024-05-17T18:00:00', 'YYYY-MM-DD"T"HH24:MI:SS'), TO_DATE('2024-05-17T19:30:00', 'YYYY-MM-DD"T"HH24:MI:SS'), 2, NULL, N'Chưa Thanh Toán', 'staff');

INSERT INTO HoaDon (MaBan, GioBatDau, GioKetThuc, KhachHang, GhiChu, TrangThaiThanhToan, TaiKhoan) 
VALUES ('BAN03', TO_DATE('2024-05-17T18:00:00', 'YYYY-MM-DD"T"HH24:MI:SS'), TO_DATE('2024-05-17T19:30:00', 'YYYY-MM-DD"T"HH24:MI:SS'), 1, NULL, N'Chưa Thanh Toán', 'huynhlong');



----- Thêm dữ liệu vào bảng ChiTietHoaDon (nếu cần)
--INSERT INTO ChiTietHoaDon (MaHoaDon, MaThucDon, SoLuongDat) VALUES (1, 'TD01', 2);
--INSERT INTO ChiTietHoaDon (MaHoaDon, MaThucDon, SoLuongDat) VALUES (7, 'TD03', 3);
--INSERT INTO ChiTietHoaDon (MaHoaDon, MaThucDon, SoLuongDat) VALUES (8, 'TD02', 3);


